### ISSUE TITLE
[Feat] 마이 페이지, 채널 생성 페이지, 사용자 정보 수정 페이지

### ISSUE THREAD

**Issue by khakisage** [JurinApp/FE_REPO#2]
## Task
- [x] 마이 페이지 CSS
- [x] 채널 생성 페이지 CSS
- [x] 사용자 정보 수정 페이지 CSS
- [x] 임시 데이터 생성
- [x] 마이 페이지 기능 구현
- [x] 채널 생성 페이지 기능 구현
- [x] 사용자 정보 수정 페이지 기능 구현
